### ISSUE TITLE
Copy updates to brochure docs

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/docs.vanillaframework.io#100]
Not sure if this is the best place, but there's something things that should be corrected in the brochure theme docs:

- [x] Title should be sentence case: https://docs.vanillaframework.io/en/vanilla-brochure-theme/patterns/ticked-list
- [x] Title should be sentence case "Stepped list: detailed" https://docs.vanillaframework.io/en/vanilla-brochure-theme/patterns/stepped-list
- [x] Title should be sentence case - **always, no exceptions** https://docs.vanillaframework.io/en/vanilla-brochure-theme/patterns/split-list
- [x] There is no such thing as "Ticked List", let's refer to the same patterns the same way across docs https://docs.vanillaframework.io/en/patterns/lists
- [x] affects, not "effects" https://docs.vanillaframework.io/en/vanilla-brochure-theme/utilities/image-position
- [x] The link back to vanilla docs in sidebar should say "docs.vanillaframework.io" - see design https://github.com/ubuntudesign/vanilla-docs-theme-design/issues/5#issuecomment-297332159
- [x] Across the documentation it says in some instances "Vanilla framework", it should be "Vanilla Framework", or just "Vanilla"
- [x] The title tab of the site says "Documentation", it should be "Vanilla Brochure theme documentation"
- [x] The header should say "Brochure theme documentation"

Thank you

**Comment by anthonydillon** [comment]
All tasks complete. Well done!
