### ISSUE TITLE
Some examples are showing in brochure theme docs

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/docs.vanillaframework.io#103]
Is it because there is no example, or a mistake? 

Example: 
https://docs.vanillaframework.io/en/vanilla-brochure-theme/patterns/split-list 
https://docs.vanillaframework.io/en/vanilla-brochure-theme/patterns/stepped-list
https://docs.vanillaframework.io/en/vanilla-brochure-theme/patterns/muted-heading

**Comment by anthonydillon** [comment]
These examples are now all working.
