### ISSUE TITLE
New vertical spacing not visible in brochure docs

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/docs.vanillaframework.io#104]
For example, the hr above "Vanilla patterns" and the heading doesn't seem to have correct spacing: https://docs.vanillaframework.io/en/vanilla-brochure-theme/patterns/stepped-list

**Comment by anthonydillon** [comment]
This was complete in https://github.com/ubuntudesign/docs.vanillaframework.io/pull/110 and will be live in the next release of Vanilla.
