### ISSUE TITLE
“Visibility” link in navigation is broken

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntudesign/docs.vanillaframework.io#107]
1\. Go to any page on [docs.vanillaframework.io](https://docs.vanillaframework.io/)
2\. In the navigation sidebar, choose “Utilities” > “Visibility”

What happens: “Not Found” “The requested URL /en/utilities/visibility was not found on this server”

What should happen: Either the link is not present, or it works.

**Comment by anthonydillon** [comment]
This was fixed in this PR https://github.com/vanilla-framework/vanilla-framework/pull/1173
