### ISSUE TITLE
Improvements to layout of documentation

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/docs.vanillaframework.io#109]

**Comment by yaili** [comment]
- Using CodePen means we'd have to update code in different places
- We should use the copy to clipboard icon that we're using
- Toggle to display different viewports is nice
- Code blocks should have a maximum number of lines before it displays the see more
- Link to pattern on GitHub
- Link to report an issue on each pattern
- Link to design spec?

**Comment by bartaz** [comment]
* How the toggle should work with 'Large' setting? Vanilla large breakpoint is at 1030px which is more than the example box will have, so how will Large example be displayed? With horizontal scrollbar?

**Comment by anthonydillon** [comment]
Agreed with all points.

**Comment by anthonydillon** [comment]
This issue contains a number of large improvements to [example-js](https://github.com/canonical-webteam/example-js). I will split them out and close this issue.

**Comment by anthonydillon** [comment]
All issues have been created.
