### ISSUE TITLE
Divider component uses 'Contextual menu' title in sidebar navigation

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/docs.vanillaframework.io#113]
# 1. Bug template

## Process

1. Navigate to [docs.vanillaframework.io](https://docs.vanillaframework.io)
2. Click on 'Patterns' in sidebar navigation
3. You'll see that 'Contextual menu' is duplicated, the first one is correct and links to the 'Contextual menu' component. But when you click on the second one you see 'Divider list' component.

## Expected result
Update name in side menu to match the component.

Contextual menu > Contextual menu component
**Divider > Divider list component**

## Current result
Name in side menu doesn't match the component.

Contextual menu > Contextual menu component
**Contextual menu > Divider list component**

## Screenshot

![screen shot 2017-10-25 at 15 25 00](https://user-images.githubusercontent.com/17748020/32004151-04c12024-b999-11e7-8290-952357ab92ee.png)

**Comment by anthonydillon** [comment]
This was fixed as a previous drive by and will be live in the next release.
