### ISSUE TITLE
Link in left side navigation are not showing in the alphabetic order

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/docs.vanillaframework.io#40]
- Look at the left side nav under "Patterns"
- Top item is not showing correctly (on one occasion I saw "Image grid:, then after refreshing - "Links")
- "Buttons" link is not showing in the right place

**Comment by barrymcgee** [comment]
@yaili did you say previously that you didn't want these to display alphabetically?

**Comment by yaili** [comment]
I did, but I don't think we have time to reorder for now, so alphabetically is OK. The issue is that random pages sometimes are not in the correct alphabetical order. For instance, if I go to the demo now, "Image grid" is the first pattern, and "Buttons" is after "Grid lists"
