### ISSUE TITLE
Convert gulp task runner to run inside Docker

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/docs.vanillaframework.io#61]
This site should build and manage dependencies in the same way as Vanilla Framework does currently for consistency: https://github.com/ubuntudesign/vanilla-framework/pull/571

**Comment by nottrobin** [comment]
This is no longer relevant, as this project now only consists of [one small script](https://github.com/ubuntudesign/docs.vanillaframework.io/blob/master/build-html), and will disappear completely when it's folded into [docs.ubuntu.com](https://github.com/canonical-websites/docs.ubuntu.com).

Closing.
