### ISSUE TITLE
Typography table headings not aligning

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/docs.vanillaframework.io#71]
On this page:

https://docs.vanillaframework.io/en/base/typography

..the column headings do not line up correctly, however, the column headings look correct on Github?

https://github.com/vanilla-framework/vanilla-framework/blob/develop/docs/en/base/typography.md

**Comment by nottrobin** [comment]
@barrymcgee Is this question still relevant? If so, I don't think I understand it. <https://docs.vanillaframework.io/en/base/typography> seems to roughly reflect <https://github.com/vanilla-framework/vanilla-framework/blob/develop/docs/en/base/typography.md>

**Comment by barrymcgee** [comment]
Yes - bug still persists..

On the docs site: https://cl.ly/212O120l2X1M

On GitHub: https://cl.ly/1V122W0Y2z0G

**Comment by nottrobin** [comment]
@barrymcgee Ah I see what you mean now!

It does use a different parser to GitHub. Although, to me, the [typography page](https://github.com/vanilla-framework/vanilla-framework/blob/develop/docs/en/base/typography.md) also looks messed up on GitHub:

![typography GitHub rendering](https://assets.ubuntu.com/v1/6c34d1f5-medded-up-on-github.png)

**Comment by barrymcgee** [comment]
@nottrobin It didn't look like that previously as you'll see from my screenshot above. Not sure why it does currently.

**Comment by nottrobin** [comment]
I believe I've fixed it: https://github.com/vanilla-framework/vanilla-framework/pull/965/files

I think we should use this format for all tables in future, with a leading and following pipe - e.g. `| col1 | col2 |` - it's less confusing for the parsers.
