### ISSUE TITLE
Small screen -  Position of search bar & menu doesn't look good

### ISSUE THREAD

**Issue by joanasa89** [ubuntudesign/docs.vanillaframework.io#78]
Fix search bar & menu position. 
Make search bar full width and position menu on top right hand corner (See the attached image)

![mobile - search bar- docs](https://cloud.githubusercontent.com/assets/21334617/23700293/4cc9eb72-03ea-11e7-8292-bee48e33e666.jpg)

**Comment by nottrobin** [comment]
This issue was moved to canonical-websites/docs.ubuntu.com#46
