### ISSUE TITLE
Add run book to wiki

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/docs.vanillaframework.io#82]
If this site goes down again and Robin/Will is not available - we should have a checklist to detail:

- site is down, steps to debug
- how to release site

**Comment by nottrobin** [comment]
Here you go: https://github.com/ubuntudesign/docs.vanillaframework.io/wiki/Fixing-the-live-site

**Comment by nottrobin** [comment]
Moved to: https://github.com/ubuntudesign/docs.vanillaframework.io/wiki/Live-site-config
