### ISSUE TITLE
Add the table of contents to docs

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/docs.vanillaframework.io#84]
Like here: https://docs.ubuntu.com/maas/2.1/en/

**Comment by yaili** [comment]
@nottrobin ?

**Comment by nottrobin** [comment]
Yes, anyone can add it with 'table_of_contents: true'. I think. Just copy the frontmatter from the MAAS documents.

**Comment by Lukewh** [comment]
@yaili do we want this on every page, including the homepage?

**Comment by yaili** [comment]
@Lukewh not homepage
